//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MemStat.rc
//
#define IDC_AMOUNTMIN                   0
#define IDC_MINFREE                     0
#define IDC_HIDE                        3
#define IDC_MINIMIZE                    4
#define IDI_MEM                         102
#define IDR_TRAYMENU                    103
#define IDD_ABOUT                       104
#define IDD_CFG_ABOUT                   104
#define IDI_TRAYLOW                     107
#define IDI_TRAYOK                      108
#define IDI_TRAY                        109
#define IDD_INDICATOR                   113
#define IDD_CONFIG2                     118
#define IDD_CFG_MONITORING              118
#define IDR_CHARTMENU                   119
#define IDD_RGB                         120
#define IDR_TRAYMENU2                   120
#define IDD_MAIN                        121
#define IDD_CFG_APPEARANCE              122
#define IDR_KEYS                        125
#define IDR_MANIFEST                    127
#define IDB_ICONFONT                    129
#define IDD_BENCHMARK                   130
#define IDI_WORK                        132
#define IDI_BENCHMARK                   133
#define IDR_LOGITEMS                    134
#define IDC_MEMSIZE                     1000
#define IDD_MEMSTATUS                   1001
#define IDC_MEMFREE                     1001
#define IDD_CONFIG                      1001
#define IDD_CFG_FREEING                 1001
#define IDC_ALLOC                       1002
#define IDC_FREENOW                     1002
#define IDD_CFG_FULLINFO                1002
#define IDC_AMOUNT                      1003
#define IDC_MANUALFREE                  1003
#define IDD_CFG_ADVANCED                1003
#define IDC_SHOW                        1004
#define IDC_SHOWMANUAL                  1004
#define IDC_MAX                         1005
#define IDC_AMOUNT2                     1007
#define IDC_AMOUNTAUTO                  1007
#define IDC_FREETO                      1007
#define IDC_SHOW2                       1008
#define IDC_SHOWAUTO                    1008
#define IDC_SHOWFREETO                  1008
#define IDC_PERC                        1009
#define IDC_PERCAUTO                    1009
#define IDC_PERCFREETO                  1009
#define IDC_EMAIL                       1011
#define IDC_SHOWMIN                     1011
#define IDC_WWW                         1012
#define IDC_PRIORITY                    1012
#define IDC_PERCMIN                     1013
#define IDC_AUTOCHECK                   1014
#define IDC_AUTODISABLED                1014
#define IDC_FREEBAR                     1026
#define IDC_FREETXT                     1027
#define IDC_IBAR                        1034
#define IDC_ITXT                        1035
#define IDC_IMOVE                       1037
#define IDC_VERSTR                      1039
#define IDC_INTERVAL                    1043
#define IDC_MEMSTATSCOUNT               1044
#define IDC_MEMLOG                      1045
#define IDC_MSL                         1045
#define IDC_AOT                         1049
#define IDC_BGCOLOR                     1051
#define IDC_FGCOLOR                     1052
#define IDC_AUTOSCALE                   1053
#define IDC_CLEANDRAW                   1054
#define IDC_LINECOLOR                   1055
#define IDC_RED                         1055
#define IDC_TEXTCOLOR                   1056
#define IDC_GREEN                       1056
#define IDC_BLUE                        1057
#define IDC_GTXT                        1059
#define IDC_RTXT                        1060
#define IDC_BTXT                        1061
#define IDC_HEX                         1062
#define IDC_COLOR                       1063
#define IDC_RESTORE                     1064
#define IDC_CFGTAB                      1065
#define IDC_LOGFILE                     1066
#define IDC_BROWSE                      1067
#define IDC_MAXLOGSIZE                  1070
#define IDC_LOGLIMIT                    1071
#define IDC_LOGAPPEND                   1072
#define IDC_TOTALPM                     1074
#define IDC_FREEPM                      1075
#define IDC_UTILIZATION                 1076
#define IDC_TOTALPF                     1078
#define IDC_FREEPF                      1079
#define IDC_MSLINFO                     1081
#define IDC_ICONSTD                     1082
#define IDC_ICONBAR                     1083
#define IDC_HOTKEYCHART                 1084
#define IDC_ICONCHART                   1085
#define IDC_AUTOSTART                   1087
#define IDC_AUTOMSL                     1088
#define IDC_AUTOSAVE                    1089
#define IDC_SAVECFG                     1090
#define IDC_UNINSTALL                   1091
#define IDC_RESETCFG                    1092
#define IDC_DTPTRANSP                   1093
#define IDC_VOLCTRL                     1094
#define IDC_WINHELP                     1095
#define IDC_FASCHECK                    1096
#define IDC_FASTXT                      1098
#define IDC_FASSLIDER                   1099
#define IDC_HOTKEYFREENOW               1100
#define IDC_MFTXT                       1101
#define IDC_DISABLE_VT                  1102
#define IDC_OSVERSION                   1103
#define IDC_FREEING                     1104
#define IDC_ICONNUM                     1111
#define IDC_ICONNUM2                    1112
#define IDC_CW_BLEND                    1115
#define IDC_BLEND_FACTOR                1117
#define IDC_BLEND_PERC                  1118
#define IDC_LOGFORMAT                   1123
#define IDC_ADDITEM                     1125
#define IDC_BENCH_PERC                  1126
#define IDC_BENCH_DONE                  1127
#define IDC_BENCH_SIZE                  1128
#define IDC_BENCH_OP                    1132
#define IDC_SEQ_READ                    1133
#define IDC_I_READ                      1133
#define IDC_SEQ_WRITE                   1134
#define IDC_I_WRITE                     1134
#define IDC_RND_READ                    1135
#define IDC_I_MOVE                      1135
#define IDC_RND_WRITE                   1136
#define IDC_L_READ                      1136
#define IDC_L_WRITE                     1137
#define IDC_L_MOVE                      1138
#define IDC_PASSES_STR                  1140
#define IDC_BENCH_PASSES                1141
#define IDC_TOTAL_STR                   1142
#define IDC_BUSY_ICON                   1145
#define IDC_FREEUP                      40002
#define ID_FREENOW                      40002
#define IDC_ABOUT                       40003
#define ID_ABOUT                        40003
#define IDC_OPEN                        40004
#define ID_OPENCONFIG                   40004
#define IDC_DISABLEAUTO                 40005
#define IDC_AUTOFREE                    40006
#define ID_AUTOFREE                     40006
#define ID_MEMCHART                     40007
#define ID_OPENCONFIG2                  40008
#define ID_FIT2CHART                    40009
#define ID_CAPTION                      40010
#define ID_CONFIG2                      40011
#define ID_CONFIG                       40011
#define ID_EXIT                         40012
#define ID_HIDE                         40013
#define ID_AUTOYSCALE                   40014
#define ID_AOT                          40015
#define ID_MOVE2TRAY                    40016
#define ID_WINHELP                      40018
#define ID_SSAVER                       40019
#define ID__DISMISS                     40020
#define IDC_IS_CHIP                     40021
#define IDC_IS_FOURBARS                 40022
#define IDC_IS_MINICHART                40023
#define IDC_IS_NUMERICAL                40024
#define IDC_IS_NUMERICAL2               40025
#define ID_CFG_FREEING                  40026
#define ID_CFG_MONITORING               40027
#define ID_CFG_APPEARANCE               40028
#define ID_CFG_ADVANCED                 40029
#define ID_MEM_BENCH                    40030
#define ID__FREEUP_1MB                  40100
#define ID__FREEUP_2MB                  40101
#define ID__FREEUP_4MB                  40102
#define ID__FREEUP_8MB                  40103
#define ID__FREEUP_16MB                 40104
#define ID__FREEUP_32MB                 40105
#define ID__FREEUP_64MB                 40106
#define ID__FREEUP_128MB                40107
#define ID_FREEUP_ALLPOSSIBLE           40199
#define ID_CLEARCLIPBOARD               40200
#define ID_CANCELFREE                   40201
#define ID_LOG_FREEPM                   40202
#define ID_LOG_FREESWAP                 40203
#define ID_LOG_CURRENTTIME              40204
#define ID_LI_BOOTUP                    40205
#define ID_LOG_PMUTILIZATION            40206
#define ID_LOG_CURUSER                  40207
#define IDC_BGCAPTION                   1054
#define IDC_TEXTCAPTION                 1057
#define IDD_FORMAT                      102
#define IDC_FORMAT                      1004
#define IDC_ELEMENTS                    1006
#define IDC_OUTPUT                      1007

#include "resrc1.h"
